name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
          config: ".github/.markdownlint.json"
